# Building the docker images
- docker-compose -f docker-compose-build.yaml build --parallel

# Tagging the docker images
- docker tag udagram-api-feed udeani/udagram-api-feed:v1
- docker tag udagram-api-user udeani/udagram-api-user:v1
- docker tag udagram-frontend udeani/udagram-frontend:v1
- docker tag reverseproxy udeani/reverseproxy:v1

  # Setting the Docker credentials
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Pushing the Docker images
- docker push udeani/udagram-api-feed:v1
- docker push udeani/udagram-frontend:v1
- docker push udeani/udagram-api-user:v1
- docker push udeani/reverseproxy:v1

